version: '3'
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6011:6011"
    environment:
      - TELEGRAM_BOT_TOKEN=6401556110:AAFZs0ZcI4dX3NJ4QSo3mr3ctXbp8f_RoSo
      - TELEGRAM_CHAT_ID=-940249870
    command: ["python", "api/sentry_telegram_webhook.py"]
